### ISSUE TITLE
Simplify instantiation of `&BStr`

### ISSUE THREAD

**Issue by Byron** [BurntSushi/bstr#110]
This issue was spun off from [this comment](https://github.com/BurntSushi/bstr/issues/40#issuecomment-1178573447) which states problems with creating instances of `&BStr` if type-inference bails out. The latter is typical within `Cow` and as one side of `assert_eq!()`.

The intuitive way of doing this to me was `BStr::new("")` or `BStr::new("hello")` or `BStr::new(b"hi")`, similar to what's possible with `std::path::Path::new(…)`.

**Comment by BurntSushi** [comment]
Aye. Were there any other helper functions you defined? I think it would be helpful to see those and see if we can bring them into `bstr`.

**Comment by Byron** [comment]
I am not sure about that 😅, as for no particular reason other than some familiarity I used `fn b(s: impl AsRef<[u8]>) -> &BStr { s.into() }`.

**Comment by BurntSushi** [comment]
Ah yeah. I wasn't sure if you had helpers for things other than construction.
