### ISSUE TITLE
Point people to full `OsStr` solution

### ISSUE THREAD

**Issue by epage** [BurntSushi/bstr#116]
In the docs

> 1. One could re-implement WTF-8 and re-encode file paths on Windows to WTF-8 by accessing their underlying 16-bit integer representation. Unfortunately, this isn’t zero cost (it introduces a second WTF-8 decoding step) and it’s not clear this is a good thing to do, since WTF-8 should ideally remain an internal implementation detail.
> ...
>
> While this library may provide facilities for (1) in the future, currently, this library only provides facilities for (2) and (3).

But it leaves it at that, without a clear path forward for those that need (1).

What if the docs suggested `os_str_bytes` in the mean time?

**Comment by BurntSushi** [comment]
I'm usually a little skeptical of linking to other crates in API docs unless they're really ubiquitous, but I think I'd be okay with this specific case given that I call out the technique in the docs itself. (I believe I wrote this before `os_str_bytes` existed.)
