### ISSUE TITLE
Consider using `once_cell` instead of `lazy_static`

### ISSUE THREAD

**Issue by lopopolo** [BurntSushi/bstr#124]
Hi @BurntSushi, I don't currently use the `unicode` feature but I am looking to do so. `bstr` would be the only crate in my lockfile that uses `lazy_static`. There has been a lot of movement in the ecosystem to port over to `once_cell`. I personally think the API is nicer and the maintenance status is in a better spot. 

`once_cell` has the added benefit of being slated for inclusion into `std`, which means it has the potential to simply re-export those `std` types once they are stabilized.

`once_cell`'s MSRV is in the 1.36 range, which is compatible with the 1.60 MSRV `bstr` now has.

`rustc` is also suggesting `once_cell` for statics:

- https://github.com/rust-lang/rust/pull/100507

Here's some examples throughout the ecosystem:

- https://github.com/rustwasm/wasm-bindgen/pull/2962
- https://github.com/tikv/rust-prometheus/issues/448
- https://github.com/tokio-rs/tokio/pull/3187
- https://github.com/tokio-rs/tracing/pull/2147
- https://github.com/clap-rs/clap/issues/3828
- https://github.com/rust-lang/rustfmt/pull/5251
- https://github.com/zeromq/zmq.rs/pull/169
- https://github.com/rust-onig/rust-onig/pull/169
- https://github.com/immunant/c2rust/pull/617
- https://github.com/rust-lang/crates.io/pull/5044
- https://github.com/uutils/coreutils/pull/3704
- https://github.com/bytecodealliance/wasmtime/pull/4368
- https://github.com/seanmonstar/reqwest/pull/1565

**Comment by lopopolo** [comment]
Now that I've taken a peek at this it looks like this update would need to be made to `ucd-generate`.

**Comment by BurntSushi** [comment]
Right. The main reason why I haven't done this yet is that I just don't think it matters much. And with it coming to std, doing a migration to `once_cell` before std just seemed like churn. So I left well enough alone.

With that said, if someone wanted to submit patches to `ucd-generate` and then `bstr`, I'd do my best to get them merged.

I do expect that eventually, Real Soon Now, once `regex-automata 0.3` is out, it will have its own built-in synchronization mechanism for initializing DFAs lazily (and in a way that works without `std`). So if you wait long enough, the `lazy_static` dependency should just disappear (and won't even be replaced by `once_cell`). But I don't know when that will be. Maybe within the calendar year?

**Comment by lopopolo** [comment]
Awesome. The changes to `regex-automata` sound exciting! I'm happy to wait this one out.
