### ISSUE TITLE
Can't call ByteVec functions if ByteSlice is in scope

### ISSUE THREAD

**Issue by lespea** [BurntSushi/bstr#14]
I'm sure that I'm just doing something wrong but I can't seem to figure this out; sorry if it's just my limited understanding of rust.

Basically I want to do some simple searches against an OsStr and thought I would use this library since it handles this nicely.  This is the most distilled version I could come up with that highlights the issue ('m doing a bit more in my actual code but not too much):

```rust
use bstr::{ByteSlice, ByteVec};
use std::ffi::OsStr;

fn main() {
    let ostr = OsStr::new("test");
    let fname = ByteVec::from_os_str_lossy(ostr);

    if fname.ends_with_str(b"ext") && fname.contains_str(b"words") {
        println!("found")
    }
}
```

Trying to compile that returns this:
```
error[E0283]: type annotations required: cannot resolve `_: bstr::ext_vec::ByteVec`
 --> src/main.rs:6:17
  |
6 |     let fname = ByteVec::from_os_str_lossy(ostr);
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: required by `bstr::ext_vec::ByteVec::from_os_str_lossy`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: Could not compile `autorun_stats`.

To learn more, run the command again with --verbose.
[Finished running. Exit status: 101]
```

If I remove the ByteSlice import than it errors that I can't call contains_str as ByteSlice needs to be in scope; if I remove that call then everything is okay.

I tried a variety of different annotations in the assignment to fname but nothing I add seems to work.

I'm using rust `rustc 1.36.0` and this is a 2018 project if that matters.

**Comment by BurntSushi** [comment]
Interesting. I don't think you can use `ByteVec` explicitly like this. While there is only one implementation (for `Vec<u8>`), the compiler can't in general know which implementation to use based on the code written, from what I can tell. Instead, just use `Vec::from_os_str_lossy(ostr)` and that should work.

I'm going to mark this as a `doc` bug, since it probably seems wise to mention something about this in the docs.

**Comment by lespea** [comment]
You were correct, I called Vec::from_os_str_lossy and it compiled without issue.  Yeah probably a good idea to mention something in the docs.  Thanks for the quick response!
