### ISSUE TITLE
bstr 1.3.0 with `impl AsRef<BStr> for BStr` breaks some folks downstream

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/bstr#149]
This was noted by @freqmod in https://github.com/BurntSushi/bstr/commit/e2296b7293ba1381c800141cb7921b9629a42414#commitcomment-101324594:

> NB: This change seems to make problems for https://github.com/Byron/gitoxide among other crates.
> 
> ```
>    --> /home/frve/.cargo/registry/src/github.com-1ecc6299db9ec823/gix-glob-0.5.3/src/wildmatch.rs:270:54
>     |
> 270 | ...                   &pattern.as_ref()[p_idx + 2..closing_bracket_idx - 1];
>     |                                ^^^^^^
>     |
> help: try using a fully qualified path to specify the expected types
>     |
> 270 |                                             &<BStr as AsRef<T>>::as_ref(pattern)[p_idx + 2..closing_bracket_idx - 1];
>     |                                              +++++++++++++++++++++++++++       ~```
> ```

Unfortunately that looks like a misuse of `AsRef`. You're only supposed to use it when the target type is known, i.e., in a generic `AsRef<BStr>` context. Otherwise, you open yourself to inference failures like this when new impls are added. These sorts of type inference failures generally fall under "acceptable breakage" from a Rust API evolution perspective.

Folks seem to constantly misuse `AsRef` as "just a way to convert one type to another" instead of "as a generic that accepts any type but which always has the target type as concrete." So much so that I filed a long outstanding bug against std's docs for this a while back: https://github.com/rust-lang/rust/issues/62586

For `gix-glob` in particular, I can reproduce the above error like so:

```
$ git clone https://github.com/Byron/gitoxide
$ cd gitoxide
$ git checkout 796f2982ebc0b7682d0ee8987221fd3397e631aa
$ cargo update -p bstr
$ cargo build --manifest-path gix-glob/Cargo.toml
   Compiling gix-glob v0.5.3 (/home/andrew/clones/gitoxide/gix-glob)
error[E0282]: type annotations needed
   --> gix-glob/src/wildmatch.rs:248:62
    |
248 | ...                   let class = &pattern.as_ref()[p_idx + 2..closing_bracket_idx - 1];
    |                                            ^^^^^^
    |
help: try using a fully qualified path to specify the expected types
    |
248 |                                         let class = &<BStr as AsRef<T>>::as_ref(pattern)[p_idx + 2..closing_bracket_idx - 1];
    |                                                      +++++++++++++++++++++++++++       ~

For more information about this error, try `rustc --explain E0282`.
error: could not compile `gix-glob` due to previous error
```

The build failure can then be fixed by just using a concrete method `as_bytes()` instead of a generic `as_ref()` that relies on inferring the target type:

```
diff --git a/gix-glob/src/wildmatch.rs b/gix-glob/src/wildmatch.rs
index 1015279f2..4b2e33948 100644
--- a/gix-glob/src/wildmatch.rs
+++ b/gix-glob/src/wildmatch.rs
@@ -245,7 +245,7 @@ pub(crate) mod function {
                                             .enumerate()
                                             .peekable();
                                     } else {
-                                        let class = &pattern.as_ref()[p_idx + 2..closing_bracket_idx - 1];
+                                        let class = &pattern.as_bytes()[p_idx + 2..closing_bracket_idx - 1];
                                         match class {
                                             b"alnum" => {
                                                 if t_ch.is_ascii_alphanumeric() {
```

This is probably a `wontfix`. But I'm open to yanking if this proves to be especially disruptive. I'd rather not if I can help it though.

cc @Byron

**Comment by Byron** [comment]
Indeed, the usage is incorrect and a `gitoxide` fix is coming up. Sorry for the hassle, and thanks for the analysis.
