### ISSUE TITLE
candidate versions found which didn't match: 0.2.17, 0.2.16, 0.2.15, ...

### ISSUE THREAD

**Issue by SkyperTHC** [BurntSushi/bstr#150]
I'm not a rust person and but thought i might not be the only person who sees this:

Cargo.toml
```
bstr = "1"
```

cargo build
```
error: failed to select a version for the requirement `bstr = "=1.3.0"`
candidate versions found which didn't match: 0.2.17, 0.2.16, 0.2.15, ...
location searched: crates.io index
```

**Comment by BurntSushi** [comment]
Can you please provide a full reproduction? Also, what version of Rust are you using?

**Comment by LPGhatguy** [comment]
I hit this on a project today using Rust 1.58.1. Here is the GitHub Actions output from the MSRV build from that project: <https://github.com/rojo-rbx/rojo/actions/runs/4774441218/jobs/8488120958>

Upgrading to Rust 1.68.2 fixed the issue. It looks like Cargo filters out versions that require a newer version of Rust than what you're running. This UX seems bad, but nothing that needs to be fixed about bstr.

**Comment by BurntSushi** [comment]
@epage Sorry to ping you again, but this is another Cargo issue I'm not sure about. I believe I've run into this myself, where basically, a dependency has `rust-version` set and Cargo will just refuse to even see that crate if your version of Rust is too old. That in turn leads to really opaque errors that basically say "no version available."

I thought the main point of `rust-version` was to get an explicit error saying that the current version of Rust is too old? But it looks like Cargo is actually using it in version resolution somehow?

**Comment by epage** [comment]
No, its that the index entry is not understood by old versions of cargo.  See https://github.com/rust-lang/cargo/issues/10623

**Comment by BurntSushi** [comment]
Ah wow, didn't realize that. Thank you!
