### ISSUE TITLE
Add unescape_ascii fn

### ISSUE THREAD

**Issue by leighmcculloch** [BurntSushi/bstr#169]
The bstr crate has an `escape_ascii` function on `Bstr` which is really helpful for producing a string version of a `Bstr` that can be printed, or placed in places that only ascii can be used.

It'd be helpful if there was an `unescape_ascii` function for producing a [u8]/Bstr from the escaped string produced by `escape_ascii`.

Then it would be possible to round-trip `Bstr` into places only ascii strings can be passed.

**Comment by BurntSushi** [comment]
Can you link to the `escape_ascii` method that's in this crate that you're talking about?

**Comment by leighmcculloch** [comment]
https://docs.rs/bstr/latest/bstr/struct.BStr.html#method.escape_ascii

Although I realize now that is coming from the core lib. 😳

**Comment by BurntSushi** [comment]
Correct. It's not a method in this library. This library does have `escape_bytes` and `unescape_bytes`, though it doesn't limit itself to ASCII.

Otherwise your use case sounds more like something that is a bit niche and might be deserving of something bespoke on your end.

**Comment by leighmcculloch** [comment]
As it turns out escape_bytes is exactly what I was looking for. Thanks.
