### ISSUE TITLE
Small documentation issues.

### ISSUE THREAD

**Issue by thomcc** [BurntSushi/bstr#17]
I noticed some small documentation problems:

- The comment on `fields_with` is truncated: https://github.com/BurntSushi/bstr/blob/1d7dc1f02f92989c276a48bc09ad08352faacf3e/src/ext_slice.rs#L1076

- The comment on `Split` refers to an `F` which does not exist. https://github.com/BurntSushi/bstr/blob/1d7dc1f02f92989c276a48bc09ad08352faacf3e/src/ext_slice.rs#L3283-L3284

**Comment by BurntSushi** [comment]
Thanks for reporting! Should be all set.
