### ISSUE TITLE
`bstr::Split` should implement clone.

### ISSUE THREAD

**Issue by adriandelgado** [BurntSushi/bstr#173]
I'm using this library in this way:
```rust
for chunk in haystack.as_bytes().split_str(needle) {
  \\ ...
}
```
which is also inside another loop.
The needle is the same in every case and `Split::new` is showing up in profiling. I also tried to create a `Finder` but it only has the `find` method.

**Comment by BurntSushi** [comment]
For small things like this, you can just submit a PR.
