### ISSUE TITLE
Unsound usages of unsafe implementation from `u8` to `usize`

### ISSUE THREAD

**Issue by llooFlashooll** [BurntSushi/bstr#185]
Hi, I am scanning the bstr in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/byteset/scalar.rs:138:5: 138:26.
``` rust
unsafe fn read_unaligned_usize(ptr: *const u8) -> usize {
    (ptr as *const usize).read_unaligned()
}
```

This unsound implementation would create a misalignment issues. The `u8` only has 1 byte, while `usize` has 8 bytes.

The problematic value is further manipulated at: src/byteset/scalar.rs:138:5: 138:43

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by BurntSushi** [comment]
I don't see the issue. It's doing an unaligned read, so misalignment isn't a problem here.

**Comment by BurntSushi** [comment]
In the future, a Miri stack trace would be preferred.
