### ISSUE TITLE
Unsound usages of unsafe implementation from `[u8]` to `BStr`

### ISSUE THREAD

**Issue by llooFlashooll** [BurntSushi/bstr#186]
Hi, I am scanning the bstr in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/bstr.rs:87:32: 87:57 and src/bstr.rs:93:32: 93:57.
``` rust
pub(crate) fn from_boxed_bytes(slice: Box<[u8]>) -> Box<BStr> {
    unsafe { Box::from_raw(Box::into_raw(slice) as _) }
}

pub(crate) fn into_boxed_bytes(slice: Box<BStr>) -> Box<[u8]> {
    unsafe { Box::from_raw(Box::into_raw(slice) as _) }
}
```

This unsound implementation would create a misalignment issues. The `[u8]` and `BStr` are different types.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by BurntSushi** [comment]
[`BStr` is defined as `repr(transparent)`](https://github.com/BurntSushi/bstr/blob/4f41e0b68c9d5c2aa5e675a357b2adac75f9aa53/src/bstr.rs#L33-L36).

**Comment by BurntSushi** [comment]
In the future, a Miri stack trace would be preferred.
