### ISSUE TITLE
Compile-time asserts for alignment bitmasks

### ISSUE THREAD

**Issue by danakj** [BurntSushi/bstr#194]
Unsafe code in this crate depends on aligning various pointers to a multiple of a size, such as
https://github.com/BurntSushi/bstr/blob/3dc5939f30daa1a8a6e5cc346bb77841f19ea415/src/ascii.rs#L56
which is used as a bit mask
https://github.com/BurntSushi/bstr/blob/3dc5939f30daa1a8a6e5cc346bb77841f19ea415/src/ascii.rs#L72

This is fine iff the _size_ of the type is a power of two, but otherwise subtracting 1 does not create the bitmask that the code intended. The language guarantees that alignments are a power of two, and that sizes are a multiple of alignment, but not that sizes are also a power of two. In practice this is true today but given the soundness depends on it, having a compile-time assertion would be a benefit.

https://doc.rust-lang.org/reference/type-layout.html#size-and-alignment:
>  Alignment is measured in bytes, and must be at least 1, and always a power of 2.

> The size of a value is the offset in bytes between successive elements in an array with that item type including alignment padding. The size of a value is always a multiple of its alignment.

This was brought up by @anforowicz during unsafe code audit: https://chromium-review.googlesource.com/c/chromium/src/+/5925797/comment/5f1943ed_de1dfe5d/

**Comment by BurntSushi** [comment]
SGTM! Nice catch!
