### ISSUE TITLE
Rename `BString::pop` to `pop_char`?

### ISSUE THREAD

**Issue by matklad** [BurntSushi/bstr#2]
I think both "pops char" and "pops u8" are plausible semantics for `pop`, so perhaps it makes sense to disambiguate the name? We can also make this symmetric and have `pop_byte, push_byte, pop_char, push_char`.

**Comment by BurntSushi** [comment]
Yeah, I agree. This is probably an oversight. I think I originally had a single `push`, but when I split that into two methods, I didn't do the same thing for `pop`. We can just deprecate `pop` and add `pop_byte` and `pop_char`.
