### ISSUE TITLE
bstr transmute

### ISSUE THREAD

**Issue by leo60228** [BurntSushi/bstr#26]
Isn't transmuting an `&[u8]` into an `&BStr` only safe if BStr is `#[repr(transparent)]`?

**Comment by leo60228** [comment]
In this context, it means that they want a way to set `#[repr(transparent)]` without it being considered public, in case they want to change the memory representation of CStr. With the stability rules, adding and later removing `#[repr(transparent)] would be a breaking change. However, if you expect BStr to always have an identical layout to `[u8]` (which I believe is the intention), it should be fine.

**Comment by BurntSushi** [comment]
Ah I see. Yeah, we should be good to add `repr(transparent)` then.
