### ISSUE TITLE
Add function for counting number of times a given byte appears in a byte_string

### ISSUE THREAD

**Issue by thomcc** [BurntSushi/bstr#27]
I wanted this to count lines, and it seems like a good fit for this library that AFAICT isn't already offered.

I initially was going to do this as just memchr_iter(...).count() and submit a PR, with the hope that in practice it would be enough faster than the `haystack.iter().filter(|&&t| t == needle).count()` for it to be fine on its own. That said, when I added the benchmarks for that, it's turns out not to be any better than the naive in a lot of cases (which makes sense, you don't want to pay for the overhead of entering the loop so often).

Anyway https://github.com/thomcc/bstr/tree/count_byte has benchmarks set up and such if that helps, I can also submit that as a PR if you'd rather take it's implementation and optimize later.

The results of the benchmark on my machine are
```
bstr/count_byte/missing time:   [10.839 ns 10.944 ns 11.081 ns]
                        thrpt:  [84.131 GiB/s 85.185 GiB/s 86.011 GiB/s]
                 change:
                        time:   [-0.6860% +2.3142% +5.4224%] (p = 0.13 > 0.05)
                        thrpt:  [-5.1435% -2.2618% +0.6907%]
                        No change in performance detected.
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) high mild
  4 (4.00%) high severe

bstr/count_byte/normal  time:   [148.13 us 149.44 us 151.18 us]
                        thrpt:  [3.1541 GiB/s 3.1909 GiB/s 3.2190 GiB/s]
                 change:
                        time:   [-0.4056% +1.6184% +4.1171%] (p = 0.14 > 0.05)
                        thrpt:  [-3.9543% -1.5926% +0.4072%]
                        No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  6 (6.00%) high severe

bstr/count_byte/frequent
                        time:   [4.4084 us 4.4287 us 4.4499 us]
                        thrpt:  [214.53 MiB/s 215.56 MiB/s 216.55 MiB/s]
                 change:
                        time:   [-2.4995% +0.8563% +4.8377%] (p = 0.68 > 0.05)
                        thrpt:  [-4.6144% -0.8490% +2.5635%]
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe

std/count_byte/missing  time:   [276.77 ns 279.35 ns 282.68 ns]
                        thrpt:  [3.2979 GiB/s 3.3372 GiB/s 3.3683 GiB/s]
                 change:
                        time:   [+0.2130% +3.5072% +6.5533%] (p = 0.04 < 0.05)
                        thrpt:  [-6.1503% -3.3884% -0.2125%]
                        Change within noise threshold.
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) high mild
  8 (8.00%) high severe

std/count_byte/normal   time:   [137.53 us 138.13 us 138.77 us]
                        thrpt:  [3.4362 GiB/s 3.4520 GiB/s 3.4670 GiB/s]
                 change:
                        time:   [-0.9794% +1.2840% +3.7289%] (p = 0.29 > 0.05)
                        thrpt:  [-3.5948% -1.2677% +0.9891%]
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe

std/count_byte/frequent time:   [284.68 ns 286.55 ns 288.44 ns]
                        thrpt:  [3.2321 GiB/s 3.2533 GiB/s 3.2747 GiB/s]
                 change:
                        time:   [-1.0976% +2.6418% +5.8560%] (p = 0.15 > 0.05)
                        thrpt:  [-5.5320% -2.5738% +1.1098%]
                        No change in performance detected.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe
```
which are somewhat damning. In particular, it only being faster in the case where the item being searched for doesn't seem that useful.

(I also started poking at an optimized usize-bytes-at-a-time implementation, but couldn't work out the bugs in it, and at this point have spent too much time on this -- that said, if looking at someones half-working SWAR code sounds useful somehow, then https://gist.github.com/thomcc/ab4c9d4509e58912feaf0c538a071b81 is available).

**Comment by BurntSushi** [comment]
Thanks for the analysis!

My main thought here is: why not use [`bytecount`](https://docs.rs/bytecount/0.6.0/bytecount/) for this, if extreme performance is that important? This is what ripgrep uses to count lines, for example.

It would be plausible for bstr to take on a dependency for `bytecount`, but I am trying desperately not to add more dependencies.

**Comment by thomcc** [comment]
Ah, fair. I didn't know that crate existed (guess I should have searched harder). 

I'm also trying to avoid the extra dep (already had bstr), so I do sympathize.
