### ISSUE TITLE
Unicode width of a byte slice?

### ISSUE THREAD

**Issue by thomcc** [BurntSushi/bstr#28]
I have some probably-utf8 bytes I'd like to know the display width for when rendered with a fixed-width font.

I could use bstr to iterate over the chars, and then use the unicode-width on each char, but this is less efficient than an implementation that skips over chunks that are all printable ASCII (which is the common case).

This seems like similar rationale to why some of the other unicode things are in here, but I wanted to know if a PR implementing this would be accepted before doing anything.

---

There are some subtleties which might it less desirable to support this, so I'll be up front about them: the value for width is defined to differ in CJK and non-CJK contexts (See http://www.unicode.org/reports/tr11/#ED6). In particular, there are a number of "ambiguous" characters, who are considered "wide" in CJK contexts and "narrow" otherwise.  

So I think the API would look something like `fn unicode_width(&self, cjk: bool) -> usize`. It's worth noting that the `unicode-width` crate exposes separate functions, but having one be the default feels a little non-ideal, and this reduces the API surface anyway. An enum would also work but the only name I can think of for the non-cjk variant is, well, `NonCjk` (to be clear: `Latin` wouldn't be accurate). So, a bool punts on having to make that decision, even though it might be considered slightly opaque.

---

For some background for why I want it: my actual use case here involves printing some data which has evolved from "ascii-by-convention" to "utf8-by-convention"\* to in a terminal application\*\*.

\* In general, bstr has been more or less perfect for this kind of data, which is common in old unixy systems and formats. This also means I only really need the non-cjk version of this, but providing one without the other seems pretty bad to me.

\*\* All the normal terminal caveats like term locale and escape codes and the like are already handled or not relevant, and I'm aware that "width" is ultimately dependent on many things including the font, the renderer being used, etc.

**Comment by BurntSushi** [comment]
> This seems like similar rationale to why some of the other unicode things are in here, but I wanted to know if a PR implementing this would be accepted before doing anything.

Yes, indeed. I believe what you've outlined is a good fit for bstr.

> So I think the API would look something like fn unicode_width(&self, cjk: bool) -> usize. It's worth noting that the unicode-width crate exposes separate functions, but having one be the default feels a little non-ideal, and this reduces the API surface anyway. An enum would also work but the only name I can think of for the non-cjk variant is, well, NonCjk (to be clear: Latin wouldn't be accurate). So, a bool punts on having to make that decision, even though it might be considered slightly opaque.

Yeah, I think using a `bool` here is probably the worst possible choice. :-( I'd really like to avoid it. What about `unicode_width_noncjk` and `unicode_width_cjk`?

**Comment by thomcc** [comment]
For an update: I've determined that what I needed was a bit more subtle than unicode width (well, I had known this, but I was hoping that it wouldn't be too hard to massage the unicode-width output into something that worked well in practice).

What I actually need/needed seems to be somewhere between a modified unicode width of the char for single-char graphemes, and 2 for any graphemes which are emoji. Additionally, I needed to allow for the chars (emoji) which had their width change in Unicode version 9. This works okay but is very ad-hoc, and still falls over for characters like e.g. ﷽ (admittedly, there may be no handling cases like that), and some others. 

Anyway I don't have an algo that I'm that happy with yet (just one that worked well enough for me to move on), and even if I did, something that ad-hoc and heuristic driven probably isn't a great fit for a lib bstr in the first place.

(All that said a spec-compliant implementation of the unicode east-asian-width computation probably still would be an okay fit for `bstr` -- it's just not a thing I'm inclined to spend effort on)

So this is a long winded way of saying I'm probably not going to be the one to fix this, and so I'm closing it for now. Feel free to reopen if you'd rather wait for someone else to do it.

**Comment by BurntSushi** [comment]
Agreed! Thank you. If someone else wants a spec compliant version, then I would still be happy to accept that for bstr.
