### ISSUE TITLE
Adding a CharOrRaw iterator

### ISSUE THREAD

**Issue by FlyingCanoe** [BurntSushi/bstr#35]
Hi @BurntSushi.

Recently I was trying to use this library to implement a Huffman coding app on a tar file. So I want to have char went it is valid utf8 and the raw byte when it is invalid. In the [doc](https://docs.rs/bstr/0.2.10/bstr/index.html) it mentions that I could use the `CharIndices` iterator and manually access the invalid byte, but that sounds like a bit of boiler plating.

I have created a pull request adding such a iterator. It is important to note that I am an inexperience programmer. In fact, if it is accepted, it will be my first contribution to an open source project.

Are they fundamental reason why such an iterator is not practical and could not be included in this project.

**Comment by BurntSushi** [comment]
> I have created a pull request adding such a iterator. It is important to note that I am an inexperience programmer. In fact, if it is accepted, it will be my first contribution to an open source project.

Looks great!

> Are they fundamental reason why such an iterator is not practical and could not be included in this project.

I wouldn't go so far as it being "fundamental," but I'm not sure I'm convinced. In general, I don't really think that a small amount of boiler plate in a somewhat uncommon case is a good reason to inflate the API. To help drive this discussion forward, could you perhaps include a code sample that uses the existing API and a code sample that uses your new API? Then we can compare them more concretely.

**Comment by FlyingCanoe** [comment]
using the existing api

[example 1](https://gist.github.com/FlyingCanoe/e3a0e3d2b8a01b8af05a914bd1099457)

using the propose api

[example 2](https://gist.github.com/FlyingCanoe/ae73d7aac83881d6078d1fa1c00b7decl)

note that using the current API I have to check to compeer the char agenste the remplacment code point wiche is a magic value

furthermore, I am not sure if this use is that uncommon for a crate like bstr. I mine, if would need to treat &[u8] as a mostly valid string I find i string that the std library don't got you cover. 

but if you need instead to interpret &[u8] as mostly text but sometime other data if find it more intuitive to got to a crate.

**Comment by BurntSushi** [comment]
Those examples aren't particularly compelling to me, since the first one is basically just a re-implementation of the API you have proposed. I was morr looking for an example of what you're actually trying to use this API for.

**Comment by FlyingCanoe** [comment]
well, the project that I am trying to use it for is currently a incomplete mess. if you still went to check it, it can be fond [here](https://github.com/FlyingCanoe/huffman_coding)

**Comment by BurntSushi** [comment]
I was hoping for a condensed example.

**Comment by BurntSushi** [comment]
Thanks for the request, but I think I'm going to pass on this. I'm not convinced this API is really worth the additional surface area at this time.

**Comment by FlyingCanoe** [comment]
sorry for not having them ready when I open this issue. there were a few thing a need to figure out in my project before I could present a working example.

[here](https://gist.github.com/FlyingCanoe/76298c84dc5993b449e39dd6602e0e7c) is a example using the current API

and [here](https://gist.github.com/FlyingCanoe/1411a75277f9801445c83db1404987a1) is a example using the propose API

Also I fond a few flaw in my original PR:

- Derive a few trait on the new type.
- I also forgot to update the crate level documentation to mention the `CharsOrRaws` iterator instead of   the `CharIndex` iterator

I can understand given the context why you would consider that it is not wort it.
In all case thank you for your time, It has bean a great learning experience.
