### ISSUE TITLE
CI workflow always uses stable Rust for all build matrixes

### ISSUE THREAD

**Issue by lopopolo** [BurntSushi/bstr#49]
The `rust` component in the build matrix is unused and instead the fixed string `stable` is given to the tool chain setup action.

This means the `pinned` build for the MSRV test builds against the latest stable.

**Comment by BurntSushi** [comment]
Blah. Thanks! Thankfully looks like nothing sneaked in that failed on 1.28.0. :) Although, I will likely be bumping the MSRV to 1.36.0 soonish.
