### ISSUE TITLE
the `Bytes` iterator should have an `as_slice` method

### ISSUE THREAD

**Issue by zserik** [BurntSushi/bstr#61]
The underlying iterator [`std::slice::Iter`](https://doc.rust-lang.org/std/slice/struct.Iter.html) has an `as_slice` method and it would be very convenient if that method would be re-exported in the `impl Bytes`, as this would allow an easy conversion between `&[u8]` and `Bytes`, which would make writing parsers easier, which often need to parse a few bytes, and then return the unparsed remaining byte slice ([example use case](https://github.com/zserik/crulz-rs/blob/16dc31b71d4a741cf8bcfaca0607122b270ccc72/src/parser.rs#L117) (currently without usage of the `Bytes` iterator)).

**Comment by BurntSushi** [comment]
Sounds like a good idea. A PR is welcome.
