### ISSUE TITLE
Feat: Box<[u8]> -> Box<BStr>

### ISSUE THREAD

**Issue by CAD97** [BurntSushi/bstr#66]
It's currently possible to do `&[u8] -> &BStr` and `Vec<[u8]> -> BString`, but a way to construct owned heap-allocated but fixed-capacity bstrings `Box<[u8]> -> Box<BStr>` is not yet provided.

**Comment by lopopolo** [comment]
As a workaround, you can go from `Vec<u8> -> BString -> Box<BStr>` with `BString::into_boxed_bstr`.
