### ISSUE TITLE
BStr Display implementation doesn't consider width and fill/align

### ISSUE THREAD

**Issue by GrayJack** [BurntSushi/bstr#69]
I tried to use the width, fill/align to print BStr and I was surprised when it didn't work.

Was this intended?

**Comment by BurntSushi** [comment]
It looks like one has to call [`std::fmt::Formatter.pad`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.pad) with a `&str` to make it work. Not sure how to do that incrementally though. Getting this to work might require re-rolling that logic unfortunately. PRs are welcome.

**Comment by GrayJack** [comment]
Yeah, to do it incrementally, it would need to be implemented manually.

I did play around with it yesterday and I have something working, I just need to add some tests first before opening a PR
