### ISSUE TITLE
What is the intended Debug escape behavior for the BStrs that contain the Unicode replacement character?

### ISSUE THREAD

**Issue by lopopolo** [BurntSushi/bstr#72]
I've based some ident parsing code on the `fmt::Debug` impl for `&BStr`, which currently looks like this:

https://github.com/BurntSushi/bstr/blob/f56685bc0b52fcd713286355baf488709120b0ce/src/impls.rs#L331-L339

For my usecase, this wasn't quite right because all Unicode characters outside of the ASCII range are valid ident characters. This means the replacement character itself is a valid ident char if it appears in the source byteslice. I ended up with something like this:

```rust
fn is_ident_char(ch: char) -> bool {
    ch.is_alphanumeric() || ch == '_' || !ch.is_ascii()
}

fn is_ident_until(name: &[u8]) -> Option<usize> {
    // Empty strings are not idents.
    if name.is_empty() {
        return Some(0);
    }
    for (start, end, ch) in name.char_indices() {
        match ch {
            // `char_indices` uses the Unicode replacement character to indicate
            // the current char is invalid UTF-8. However, the replacement
            // character itself _is_ valid UTF-8 and a valid Ruby identifier.
            //
            // If `char_indices` yields a replacement char and the byte span
            // matches the UTF-8 encoding of the replacement char, continue.
            REPLACEMENT_CHARACTER if name[start..end] == REPLACEMENT_CHARACTER_BYTES[..] => {}
            // Otherwise, we've gotten invalid UTF-8, which means this is not an
            // ident.
            REPLACEMENT_CHARACTER => return Some(start),
            ch if !is_ident_char(ch) => return Some(start),
            _ => {}
        }
    }
    None
}
```

The current implementation of `Debug` will always output the replacement character as three byte escapes. Is this intended?

**Comment by BurntSushi** [comment]
> The current implementation of Debug will always output the replacement character as three byte escapes. Is this intended?

I would say probably not. It's a good point. I think something like your approach would work well: check if the bytes correspond to the UTF-8 encoding of the replacement codepoint, and if so, escape it like any other codepoint. Otherwise, right the raw bytes.

**Comment by lopopolo** [comment]
As an aside, I now know that `\uFFFD` is the replacement character after diving through the `bstr` source, but there is a `core::char::REPLACEMENT_CHARACTER` constant that I think would be nicer to use instead. I'm not sure if using it has MSRV implications.

**Comment by BurntSushi** [comment]
@lopopolo Yeah, using the constant is probably the better thing to do. If you work with Unicode and UTF-8 as much as I do, then `\uFFFD` just becomes as natural as breathing! Hah. But yeah, a named constant would be clearer. It would be fine to use, since that constant was introduced in Rust 1.9. bstr's MSRV is much higher than that.

**Comment by lopopolo** [comment]
The `CharIndices` iterator is also used by:

- `ByteSlice::to_lowercase_into`
- `ByteSlice::to_uppercase_into`

They are not impacted by this bug, but I think adding a comment like this would be a good idea:

```rust
            // This branch coaleces invalid UTF-8 bytes and legitimate
            // occurrences of the Unicode replacement character. This is
            // acceptable since the replacement character does not lowercase
            // into a different character
            if ch == '\u{FFFD}' {
```
