### ISSUE TITLE
Consider impl AsRef<OsStr> for BStr/BString

### ISSUE THREAD

**Issue by joshtriplett** [BurntSushi/bstr#75]
I'd like to be able to pass a `Vec<BString>` directly to [`Command::args`](https://doc.rust-lang.org/std/process/struct.Command.html#method.args), or to [other methods](https://docs.rs/unshare/0.5.1/unshare/struct.Command.html#method.args) that want a `&[T]` for some `T: AsRef<OsStr>`. The easiest way to do that would be if `BString` implemented `AsRef<OsStr>`.

I realize that doing this would mask issues with invalid UTF-16 on Windows, but from what I understand, those are *incredibly* uncommon to encounter and difficult to create (unlike invalid UTF-8 on UNIX, which is quite easy to end up with).

Would you consider providing such an impl?

**Comment by BurntSushi** [comment]
Even if we were willing to mask issues (I'm not sure that I would be), I still don't quite see how this can be done. If the bstring contains invalid UTF-8, then what do you do? More generally how would this even be implemented correctly on Windows if it were valid UTF-8?

**Comment by joshtriplett** [comment]
> If the bstring contains invalid UTF-8, then what do you do?

> More generally how would this even be implemented correctly on Windows if it were valid UTF-8?

Ah, I see what you're getting at.

On non-Windows, OsStr doesn't guarantee UTF-8 either, and specifically can contain arbitrary bytes, so I'd expect to end up with an OsStr containing exactly the bytes in the BString. And on Windows, valid UTF-8 shouldn't be an issue either (modulo the non-existence of a `from_wtf8` method, but that should be fixable).

But the case that'd be a problem would be invalid UTF-8 on Windows. Digging into it further, I hadn't realized that on Windows, OsStr was *required* to be WTF-8, not just a bag of bytes. It'd be possible to convert in a reasonable, well-defined way, but not via an `AsRef` in-place reinterpretation.

**Comment by BurntSushi** [comment]
Yes exactly. And the absence of a from_wtf8 is not necessarily fixable because as of now its absence is an explicit design decision (and similarly for the absence of an as_wtf8 method). Although I am a weak advocate in favor of adding them.
