### ISSUE TITLE
Reverse word-based iterators?

### ISSUE THREAD

**Issue by wfchandler** [BurntSushi/bstr#78]
First, thanks for creating bstr, it's great!

I'm working with a data with long lines that contain relevant data at the end.  It would be useful to be able to iterate over words in reverse, e.g. a `WordsReverse` or `FieldsReverse`.  Currently I handle this using `rsplit` on ' ', but this doesn't cope with multiple spaces and feels brittle.

Are there any technical reasons these structs don't exist?  If not, would you be open to a PR to add them?

**Comment by BurntSushi** [comment]
IIRC, I didn't add it for a few reasons:

1. It wasn't clear that it was worth it.
2. I wasn't particularly motivated to do it at the time. If you [look at the regex for it](https://github.com/BurntSushi/bstr/blob/7f0ad15d9628c0abec8cf6b7585539cae63e6d5b/scripts/regex/word.sh), it should be clear why. :-)
3. Actually generating the reverse DFA should be pretty simply by [copying how it's done for graphemes](https://github.com/BurntSushi/bstr/blob/7f0ad15d9628c0abec8cf6b7585539cae63e6d5b/scripts/generate-unicode-data#L38-L44). IIRC, I tried this for the word and sentence iterators and was miffed at how large the DFAs were and considered it impractical to bundle them with bstr.

Ah yeah, [looking at the comment in `word.sh`](https://github.com/BurntSushi/bstr/blob/7f0ad15d9628c0abec8cf6b7585539cae63e6d5b/scripts/regex/word.sh#L19-L31) leaves a trail of breadcrumbs about my thinking:

> In general, I consider this approach to be a failure. Firstly, this is
> clearly a write-only regex. Secondly, building the minimized DFA for this is
> incredibly slow. Thirdly, the DFA is itself very large (~240KB). Fourthly,
> reversing this regex (for reverse word iteration) results in a >19MB DFA.
> Yes. That's MB. Wat. And it took 5 minutes to build.
>
> I think we might consider changing our approach to this problem. The normal
> path I've seen, I think, is to decode codepoints one at a time, and then
> thread them through a state machine in the code itself. We could take this
> approach, or possibly combine it with a DFA that tells us which Word_Break
> value a codepoint has. I'd prefer the latter approach, but it requires adding
> RegexSet support to regex-automata. Something that should definitely be done,
> but is a fair amount of work.
>
> Gah.

So yeah, it looks like the easiest way to add this is to bundle a 19MB binary file with bstr. I personally consider that a non-starter. And the regex-automata refactor isn't complete yet and won't be for a while.

**Comment by wfchandler** [comment]
Thanks for the quick and thorough response.  Given that this won't be feasible without a significant amount of work, I'll go ahead and close out the issue.

Thanks again!
