### ISSUE TITLE
no_std + alloc cargo feature configuration

### ISSUE THREAD

**Issue by lopopolo** [BurntSushi/bstr#79]
I would like to use `bstr` to implement a [conventionally UTF-8 `String` data structure](https://ruby-doc.org/core-2.6.3/String.html) to be used in a [Rust implementation of Ruby](https://github.com/artichoke/artichoke).

As I've been implementing the core data structures in Artichoke, I've made as many of them as I can `#[no_std]` (for example, [this `Array` implementation built with `Vec`](https://github.com/artichoke/artichoke/blob/1f31c37d1762fe6c109525bd03d38f47bd214b3c/spinoso-array/src/lib.rs#L135-L136)).

The `ByteVec` extension trait has several methods I'd like to use instead of reimplementing myself, such as `ByteVec::remove_char`. Unfortunately, the `ByteVec` impl is gated on the `std` cargo feature which will require my crate to link to `std` despite my interest in only linking to `alloc`. For this `String` data structure, I am not interested in any of the `PathBuf` or `OsString` APIs.

I think this might be a breaking change for 1.0, so I wanted to raise this as soon as I ran into it.

**Comment by BurntSushi** [comment]
This sounds prudent. I don't think it would be a breaking change though?

Out of curiosity, why aren't you using std in your implementation of Ruby?

**Comment by lopopolo** [comment]
> I don't think it would be a breaking change though?

Oh that might be right. I guess `alloc` is a subset of an already-default `std` feature and adding the `alloc` feature wouldn't break folks using either `default-features = false` or `default-features = false, features = ["std"]`.

> Out of curiosity, why aren't you using std in your implementation of Ruby?

Of the core APIs, only a few require `std` like `ENV`, `File`, and `IO` (maybe `Time` depending on the crate used).

Artichoke is pretty modular: each core API is implemented as its own crate, each VM is its own crate that stitches together the core API crates and exposes them to Ruby code, and a frontend crate consumes a VM to e.g. build a REPL and CLI. I'd like to make all of the core data structures `no_std` if possible to not require a full VM to require `std`.

Concretely, I'd like to build a VM for the `wasm32-unknown-unknown` target and one way to make that possible is to not include any `std`-dependent data structures.

**Comment by BurntSushi** [comment]
Excellent. Thank you for explaining!
