### ISSUE TITLE
Implement conversion of OsStr/OsString to BStr/BString when Unix

### ISSUE THREAD

**Issue by GrayJack** [BurntSushi/bstr#80]
Since on Unix systems `OsString`/`OsStr` are made of `u8`, it would be convenient to be able to convert these types to `BString` and `BStr` on Unix system.

I'm willing to implement that if considered a good addition to the crate.

**Comment by BurntSushi** [comment]
Could you please say why the [existing routines for this](https://docs.rs/bstr/0.2.14/bstr/#file-paths-and-os-strings) aren't suitable for your use case?

**Comment by GrayJack** [comment]
They are suitable to me, I was just wrongly was searching for it in a `From`/`TryFrom` implementations of `Bstr`/`BString`
