### ISSUE TITLE
Compaing Cow<BStr> to BStr fails expected behavior

### ISSUE THREAD

**Issue by rufusroflpunch** [BurntSushi/bstr#82]
bstr version: 0.2.14
rustc version: 1.49.0

When executing the following tests, I would expect the `bstr` assertion to fail, but passes, while the `str` comparison fails as expected.

```rust
#[test]
fn test_cows() {
    let c1 = Cow::from(b"hello bstr".as_bstr());
    let c2 = b"goodbye bstr".as_bstr();
    assert_eq!(c1, c2);

    let c3 = Cow::from("hello str");
    let c4 = "goodbye str";
    assert_eq!(c3, c4);
}
```

**Comment by thomcc** [comment]
Oof, https://github.com/BurntSushi/bstr/blob/master/src/impls.rs#L24-L39 looks like it compares against itself.

**Comment by BurntSushi** [comment]
The fix for this is on crates.io in `bstr 0.2.15`.
