### ISSUE TITLE
remove_char bug?

### ISSUE THREAD

**Issue by shanliu** [BurntSushi/bstr#92]
```rust
use bstr::{ByteVec};
let mut s = Vec::from("1☃☃☃");
assert_eq!(s.remove_char(3), '☃');
```
rustc 1.53.0 (53cb7b09b 2021-06-17) error detail:
thread 'test4' panicked at 'assertion failed: `(left == right)`
  left: `'�'`,
 right: `'☃'`',

**Comment by BurntSushi** [comment]
The docs for the function say, emphasis mine:

> Removes a char from this `Vec<u8>` at the given **byte position** and returns it.

The behavior you're seeing is thus correct. My guess is that you're confusing the offset for a codepoint offset. Nothing in this library uses codepoint offsets. (And you probably shouldn't be either.)
