### ISSUE TITLE
Please declare experiment a success :-)

### ISSUE THREAD

**Issue by ijackson** [BurntSushi/bstr#99]
Hi.  I wasn't previously aware of `bstr`, but a correspondent suggested that I ought to recommend it in my (soon-to-be-published) guide [Rust for the Polyglot Programmer](https://www.chiark.greenend.org.uk/~ianmdlvl/rust-polyglot/index.html).

Well, speaking personally I wish I had known about this crate sooner.  I haven't yet tried it but I was doing something just last week that I think it woud really have helped with.

So, I would really like to point my readers to `bstr` from the Libraries section of my guide.  But I'm a bit concerned about the fact that it's described very prominently as "experimental".  The crates.io download statistics suggest the experiment has been a success, and you're still on 0.2.x which suggests the API is really quite stable.

Would you care to remove the word "experimental" from the README and crate docs ? :-)

**Comment by BurntSushi** [comment]
Aye. I'll do this as part of the 1.0 release, which I hope to do "soon." Where "soon" is probably "before 2022."

I would say that, IMO, so far, it is a mild success in terms of the number of people using it. But the folks that do wind up using it do seem to feel like it is making their lives a lot easier.

**Comment by BurntSushi** [comment]
See https://github.com/BurntSushi/bstr/issues/40 for the 1.0 release. TL;DR - Only minor breaking changes are planned.

**Comment by ijackson** [comment]
OK, l thanks.  For now I have [written](https://www.chiark.greenend.org.uk/%7Eianmdlvl/rust-polyglot/libs.html#libraries-for-specific-purposes)

> Disregard the warning that it's experimental.

This is a somewhst uncomfortable thing to write.  Unwarranted 0.x very common in the Rust ecosystem, where IME a 0.x vs 1.x version number has absolutely no correlation with stability or usefulness, but it is unusual to have to explicitly warn the reader to disregard a warning!

Please let me know if you don't think what I've done is appropriate.  If you would prefer me to remove the recommendation of bstr then of course I'll do that.  Or feel free to suggest alternative wording.  Thanks.

**Comment by BurntSushi** [comment]
OK, so I went to take a look at how the word was being used. I agree that it's no longer an appropriate word to use, so I just removed it and did some light re-wording.

Fixed in `0.2.17`.

**Comment by BurntSushi** [comment]
Note that I did leave the warning about making `bstr` a public dependency. I'll remove that once 1.0 is released.

**Comment by ijackson** [comment]
Excellent.  Thank you :-).  I've removed the corresponding note from my guide.
